PROCESS BEFORE OUTPUT.
  MODULE status_0400.
  CALL SUBSCREEN sub1 INCLUDING sy-repid '0410'.
  CALL SUBSCREEN sub2 INCLUDING sy-repid '0420'.
  CALL SUBSCREEN sub3 INCLUDING sy-repid '0430'.
  CALL SUBSCREEN sub4 INCLUDING sy-repid '0440'.

PROCESS AFTER INPUT.
  MODULE user_command_0400.
  CALL SUBSCREEN sub1.
  CALL SUBSCREEN sub2.
  CALL SUBSCREEN sub3.
  CALL SUBSCREEN sub4.
